-- MySQL Script generated by MySQL Workbench
-- Wed Feb 15 19:16:22 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema NavigationProject(2203vb)
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema NavigationProject(2203vb)
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `NavigationProject(2203vb)` DEFAULT CHARACTER SET utf8 ;
USE `NavigationProject(2203vb)` ;

-- -----------------------------------------------------
-- Table `transit_points`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transit_points` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `distance_between`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `distance_between` (
  `transit_point_a_id` INT NOT NULL,
  `transit_point_b_id` INT NOT NULL,
  `distance` INT NOT NULL,
  PRIMARY KEY (`transit_point_a_id`, `transit_point_b_id`),
  INDEX `fk_distance_between_transit_points_idx` (`transit_point_b_id` ASC),
  CONSTRAINT `fk_distance_between_transit_points_a`
    FOREIGN KEY (`transit_point_a_id`)
    REFERENCES `transit_points` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_distance_between_transit_points_b`
    FOREIGN KEY (`transit_point_b_id`)
    REFERENCES `transit_points` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `travel_weights`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `travel_weights` (
  `transit_point_a_id` INT NOT NULL,
  `transit_point_b_id` INT NOT NULL,
  `car_weight` DOUBLE NULL,
  `bus_weight` DOUBLE NULL,
  `tram_weight` DOUBLE NULL,
  `metro_weight` DOUBLE NULL,
  PRIMARY KEY (`transit_point_a_id`, `transit_point_b_id`),
  INDEX `fk_travel_weights_transit_points_idx` (`transit_point_b_id` ASC),
  CONSTRAINT `fk_travel_weights_transit_points_a`
    FOREIGN KEY (`transit_point_a_id`)
    REFERENCES `transit_points` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_travel_weights_transit_points_b`
    FOREIGN KEY (`transit_point_b_id`)
    REFERENCES `transit_points` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bus_routes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bus_routes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `route_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tram_routes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tram_routes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `route_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `metro_routes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `metro_routes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `route_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bus_stops`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bus_stops` (
  `bus_route_id` INT NOT NULL,
  `transit_point_id` INT NOT NULL,
  `stop_no` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`bus_route_id`, `transit_point_id`),
  INDEX `fk_bus_stops_transit_points_idx` (`transit_point_id` ASC),
  INDEX `fk_bus_stops_bus_routes_idx` (`bus_route_id` ASC),
  CONSTRAINT `fk_bus_stops_bus_routes`
    FOREIGN KEY (`bus_route_id`)
    REFERENCES `bus_routes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_bus_stops_transit_points`
    FOREIGN KEY (`transit_point_id`)
    REFERENCES `transit_points` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tram_stops`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tram_stops` (
  `tram_route_id` INT NOT NULL,
  `transit_point_id` INT NOT NULL,
  `stop_no` INT NOT NULL,
  PRIMARY KEY (`tram_route_id`, `transit_point_id`),
  INDEX `fk_tram_stops_transit_points_idx` (`transit_point_id` ASC),
  INDEX `fk_tram_stops_tram_routes_idx` (`tram_route_id` ASC),
  CONSTRAINT `fk_tram_stop_tram_routes`
    FOREIGN KEY (`tram_route_id`)
    REFERENCES `tram_routes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tram_stop_transit_points`
    FOREIGN KEY (`transit_point_id`)
    REFERENCES `transit_points` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `metro_stops`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `metro_stops` (
  `metro_route_id` INT NOT NULL,
  `transit_point_id` INT NOT NULL,
  `stop_no` INT NOT NULL,
  PRIMARY KEY (`metro_route_id`, `transit_point_id`),
  INDEX `fk_metro_stops_transit_points_idx` (`transit_point_id` ASC),
  INDEX `fk_metro_stops_metro_routes_idx` (`metro_route_id` ASC),
  CONSTRAINT `fk_metro_stops_metro_routes`
    FOREIGN KEY (`metro_route_id`)
    REFERENCES `metro_routes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_metro_stops_transit_points`
    FOREIGN KEY (`transit_point_id`)
    REFERENCES `transit_points` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
